"""init: create agents, contract_history, audit_logs

Revision ID: 4e303a674a86
Revises: 
Create Date: 2026-03-20 13:51:36.762364

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4e303a674a86'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agents',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('agent_id', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('callback_url', sa.Text(), nullable=False),
    sa.Column('skills', sa.JSON(), server_default='[]', nullable=True),
    sa.Column('data_contract', sa.JSON(), nullable=False),
    sa.Column('domain', sa.String(length=255), nullable=True),
    sa.Column('api_key_hash', sa.String(length=255), nullable=False),
    sa.Column('hub_shared_secret_hash', sa.String(length=255), nullable=False),
    sa.Column('scopes', sa.JSON(), server_default='["publish","query","discover","subscribe","audit"]', nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agents_agent_id'), 'agents', ['agent_id'], unique=True)
    op.create_index(op.f('ix_agents_domain'), 'agents', ['domain'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('timestamp', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('source_agent', sa.String(length=255), nullable=True),
    sa.Column('target_agent', sa.String(length=255), nullable=True),
    sa.Column('schema_id', sa.String(length=255), nullable=True),
    sa.Column('action_type', sa.String(length=50), nullable=True),
    sa.Column('decision', sa.String(length=50), nullable=True),
    sa.Column('policy_matched', sa.String(length=255), nullable=True),
    sa.Column('transforms_applied', sa.JSON(), server_default='[]', nullable=True),
    sa.Column('request_id', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('request_id')
    )
    op.create_index(op.f('ix_audit_logs_action_type'), 'audit_logs', ['action_type'], unique=False)
    op.create_index(op.f('ix_audit_logs_source_agent'), 'audit_logs', ['source_agent'], unique=False)
    op.create_index(op.f('ix_audit_logs_target_agent'), 'audit_logs', ['target_agent'], unique=False)
    op.create_index(op.f('ix_audit_logs_timestamp'), 'audit_logs', ['timestamp'], unique=False)
    op.create_table('contract_history',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('agent_id', sa.String(length=255), nullable=False),
    sa.Column('version', sa.String(length=50), nullable=False),
    sa.Column('contract_data', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contract_history_agent_id'), 'contract_history', ['agent_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_contract_history_agent_id'), table_name='contract_history')
    op.drop_table('contract_history')
    op.drop_index(op.f('ix_audit_logs_timestamp'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_target_agent'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_source_agent'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action_type'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_agents_domain'), table_name='agents')
    op.drop_index(op.f('ix_agents_agent_id'), table_name='agents')
    op.drop_table('agents')
    # ### end Alembic commands ###
